name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokeappfull" 
          heroku_email: "david_lion_ig@outlook.com.pe"
          healthcheck: "https://pokeappfull.herokuapp.com/health"
          checkstring: "check"
          rollbackonhealthcheckfailed: true
